#14: Exclude tests from compilation
foundernest/simple-queue-decorator pull request #15
Opened 2019-10-11 14:21 UTC by Agreon

2019-10-11 21:40 UTC, angrykoala commented
Thanks for your contribution @Agreon 

Please, could you make the PR to `dev` branch instead of `master?
Thanks

2019-10-11 21:48 UTC, angrykoala requested changes
Would it be worth it to add a new step `npm run tsc` in .travis.yml to ensure the build is working in the CI?

2019-10-11 21:48 UTC, angrykoala commented on tsconfig.json
> +  "include": ["./src/**/*.ts"]
this setting won't include index.ts, which is required for the build to work

2019-10-11 21:48 UTC, angrykoala commented on package.json
>      "prepublishOnly": "npm run tslint && npm test"
Because `npm test` no longer execute `tsc`, prepublishOnly should run it after tslint and tests are OK

2019-10-12 05:24 UTC, Agreon commented
Sorry i must have overlooked the index.ts.

I don't think it is worth it, as it would not fail if the index.ts is missing for example. Otherwise i would have noticed.

2019-10-12 10:53 UTC, merged